---
- name: Deploy cron script
  template:
    src: 'restic.cron.j2'
    dest: '/etc/cron.d/restic-{{ item.name }}'
    mode: '0640'
  no_log: true

- name: Deploy helper commands
  template:
    src: 'restic.helper.j2'
    dest: "{{ restic_install_path }}/restic-{{ item.name }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: '0750'
  no_log: true

- name: Check if repo is already initialized
  command: restic -r {{ item.url | trim | quote }} snapshots
  environment:
    RESTIC_PASSWORD: "{{ item.password | trim | quote }}"
  changed_when: false
  failed_when: false
  check_mode: false
  no_log: true
  register: repo

- name: Initialize restic repositories
  command: "{{ restic_install_path }}/restic-{{ item.name }} init"
  ignore_errors: true
  no_log: true
  when:
    - repo.rc != 0
    - restic_initialize_repos
