---
- name: Default use-case scenario
  hosts: all
  any_errors_fatal: true
  roles:
    - ansible-restic
  vars:
    restic_user: restic
    restic_group: restic
    restic_repos:
      - name: s3-example
        url: "s3:s3.amazonaws.com/bucket_name/restic"
        password: "correcthorsebatterystaple"
        remote_credentials:
          aws_secret_key_id: "AWS_ACCESS_KEY_ID"
          aws_secret_access_key: "AWS_SECRET_ACCESS_KEY"
        jobs:
          - command: 'restic backup /srv'
            at: '0 1  * * *'
        retention_time: '17 5 * * *'
        retention:
          last: 2
          hourly: 4
          weekly: 9
          monthly: 3
          yearly: 10
          tags:
            - special
            - test
      - name: backblaze-example
        url: "b2:bucketname:path/to/repo"
        password: "correcthorsebatterystaple"
        remote_credentials:
          b2_account_id: "B2_ACCOUNT_ID"
          b2_account_key: "B2_ACCOUNT_KEY"
        jobs:
          - command: 'restic backup /var'
            at: '0 4  * * *'
          - command: 'restic backup /home'
            at: '0 3  * * *'
            user: 'restic'
